package com.blezzdev.vjade.core.input;

import static org.lwjgl.glfw.GLFW.*;

public class Keyboard {
    public static int ZERO = GLFW_KEY_0,
            ONE = GLFW_KEY_1,
            TWO = GLFW_KEY_2,
            THREE = GLFW_KEY_3,
            FOUR = GLFW_KEY_4,
            FIVE = GLFW_KEY_5,
            SIX = GLFW_KEY_6,
            SEVEN = GLFW_KEY_7,
            EIGHT = GLFW_KEY_8,
            NINE = GLFW_KEY_9,

    ESCAPE = GLFW_KEY_ESCAPE,
            F1 = GLFW_KEY_F1,
            F2 = GLFW_KEY_F2,
            F3 = GLFW_KEY_F3,
            F4 = GLFW_KEY_F4,
            F5 = GLFW_KEY_F5,
            F6 = GLFW_KEY_F6,
            F7 = GLFW_KEY_F7,
            F8 = GLFW_KEY_F8,
            F9 = GLFW_KEY_F9,
            F10 = GLFW_KEY_F10,
            F11 = GLFW_KEY_F11,
            F12 = GLFW_KEY_F12,
            F13 = GLFW_KEY_F13,
            F14 = GLFW_KEY_F14,
            F15 = GLFW_KEY_F15,
            F16 = GLFW_KEY_F16,
            F17 = GLFW_KEY_F17,
            F18 = GLFW_KEY_F18,
            F19 = GLFW_KEY_F19,
            F20 = GLFW_KEY_F20,
            F21 = GLFW_KEY_F21,
            F22 = GLFW_KEY_F22,
            F23 = GLFW_KEY_F23,
            F24 = GLFW_KEY_F24,
            F25 = GLFW_KEY_F25,

    Q = GLFW_KEY_Q,
            W = GLFW_KEY_W,
            E = GLFW_KEY_E,
            R = GLFW_KEY_R,
            T = GLFW_KEY_T,
            Y = GLFW_KEY_Y,
            U = GLFW_KEY_U,
            I = GLFW_KEY_Y,
            O = GLFW_KEY_O,
            P = GLFW_KEY_P,
            A = GLFW_KEY_A,
            S = GLFW_KEY_S,
            D = GLFW_KEY_D,
            F = GLFW_KEY_F,
            G = GLFW_KEY_G,
            H = GLFW_KEY_H,
            J = GLFW_KEY_J,
            K = GLFW_KEY_K,
            L = GLFW_KEY_L,
            Z = GLFW_KEY_Z,
            X = GLFW_KEY_X,
            C = GLFW_KEY_C,
            V = GLFW_KEY_V,
            B = GLFW_KEY_B,
            N = GLFW_KEY_N,
            M = GLFW_KEY_M,

    TAB = GLFW_KEY_TAB,
            LEFT_SHIFT = GLFW_KEY_LEFT_SHIFT,
            LEFT_CONTROL = GLFW_KEY_LEFT_CONTROL,
            LEFT_ALT = GLFW_KEY_LEFT_ALT,
            LEFT_SUPER = GLFW_KEY_LEFT_SUPER,
            SPACE = GLFW_KEY_SPACE,
            RIGHT_SUPER = GLFW_KEY_RIGHT_SUPER,
            RIGHT_ALT = GLFW_KEY_RIGHT_ALT,
            RIGHT_CONTROL = GLFW_KEY_RIGHT_CONTROL,
            RIGHT_SHIFT = GLFW_KEY_RIGHT_SHIFT,
            ENTER = GLFW_KEY_ENTER,

    UP_ARROW = GLFW_KEY_UP,
            DOWN_ARROW = GLFW_KEY_DOWN,
            LEFT_ARROW = GLFW_KEY_LEFT,
            RIGHT_ARROW = GLFW_KEY_RIGHT,

    MINUS = GLFW_KEY_MINUS,
            CAPS_LOCK = GLFW_KEY_CAPS_LOCK,
            NUMBER_LOCK = GLFW_KEY_NUM_LOCK,
            SCROLL_LOCK = GLFW_KEY_SCROLL_LOCK,

    COMMA = GLFW_KEY_COMMA,
            SEMICOLON = GLFW_KEY_SEMICOLON,

    NUMERIC_KEYPAD_0 = GLFW_KEY_KP_0,
            NUMERIC_KEYPAD_1 = GLFW_KEY_KP_1,
            NUMERIC_KEYPAD_2 = GLFW_KEY_KP_2,
            NUMERIC_KEYPAD_3 = GLFW_KEY_KP_3,
            NUMERIC_KEYPAD_4 = GLFW_KEY_KP_4,
            NUMERIC_KEYPAD_5 = GLFW_KEY_KP_5,
            NUMERIC_KEYPAD_6 = GLFW_KEY_KP_6,
            NUMERIC_KEYPAD_7 = GLFW_KEY_KP_7,
            NUMERIC_KEYPAD_8 = GLFW_KEY_KP_8,
            NUMERIC_KEYPAD_9 = GLFW_KEY_KP_9,
            NUMERIC_KEYPAD_ADD = GLFW_KEY_KP_ADD,
            NUMERIC_KEYPAD_SUBTRACT = GLFW_KEY_KP_SUBTRACT,
            NUMERIC_KEYPAD_MULTIPLY = GLFW_KEY_KP_MULTIPLY,
            NUMERIC_KEYPAD_DIVIDE = GLFW_KEY_KP_DIVIDE,
            NUMERIC_KEYPAD_DOT = GLFW_KEY_KP_DECIMAL,
            NUMERIC_KEYPAD_ENTER = GLFW_KEY_KP_ENTER,
            NUMERIC_KEYPAD_EQUAL = GLFW_KEY_KP_EQUAL,

    INSERT = GLFW_KEY_INSERT,
            PRINT_SCREEN = GLFW_KEY_PRINT_SCREEN,
            PAUSE = GLFW_KEY_PAUSE,
            END = GLFW_KEY_END,
            DELETE = GLFW_KEY_DELETE,
            PAGE_DOWN = GLFW_KEY_PAGE_DOWN,
            PAGE_UP = GLFW_KEY_PAGE_UP;
}