package com.blezzdev.vjade.core.input;

import static org.lwjgl.glfw.GLFW.*;

public class Mouse {
    public static int LEFT_BUTTON = GLFW_MOUSE_BUTTON_LEFT,
            MIDDLE_BUTTON = GLFW_MOUSE_BUTTON_MIDDLE,
            RIGHT_BUTTON = GLFW_MOUSE_BUTTON_RIGHT,

    ONE_BUTTON = GLFW_MOUSE_BUTTON_1,
            TWO_BUTTON = GLFW_MOUSE_BUTTON_2,
            THREE_BUTTON = GLFW_MOUSE_BUTTON_3,
            FOUR_BUTTON = GLFW_MOUSE_BUTTON_4,
            FIVE_BUTTON = GLFW_MOUSE_BUTTON_5,
            SIX_BUTTON = GLFW_MOUSE_BUTTON_6,
            SEVEN_BUTTON = GLFW_MOUSE_BUTTON_7,
            EIGHT_BUTTON = GLFW_MOUSE_BUTTON_8,

    DEFAULT_CURSOR = GLFW_ARROW_CURSOR,
            ALL_RESIZE_CURSOR = GLFW_RESIZE_ALL_CURSOR,
            CROSSHAIR_CURSOR = GLFW_CROSSHAIR_CURSOR,
            WRITABLE_CURSOR = GLFW_IBEAM_CURSOR,
            NOT_ALLOWED_CURSOR = GLFW_NOT_ALLOWED_CURSOR,
            POINTING_HAND_CURSOR = GLFW_POINTING_HAND_CURSOR,
            VERTICAL_RESIZE_CURSOR = GLFW_RESIZE_NS_CURSOR,
            HORIZONTAL_CURSOR = GLFW_RESIZE_EW_CURSOR,
            CORNER_BOT_TOP_RESIZE_CURSOR = GLFW_RESIZE_NESW_CURSOR,
            CORNER_TOP_BOT_RESIZE_CURSOR = GLFW_RESIZE_NWSE_CURSOR;
}
